---
name: Build and Push devcontainer

on:
  repository_dispatch:
    types: [features]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/devcontainer/.devcontainer/devcontainer.json'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push:
    timeout-minutes: 1440
    runs-on: CLOUDSHELL
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: "ghcr.io"
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: |
          /usr/local/nvm/versions/node/v24.6.0/bin/devcontainer build \
            --workspace-folder src/devcontainer \
            --image-name ghcr.io/${{ github.repository_owner }}/devcontainer \
            --platform linux/amd64 \
            --output type=docker \
            --cache-from ghcr.io/40docs/devcontainer:latest
          docker tag ghcr.io/40docs/devcontainer ghcr.io/40docs/devcontainer:latest
          docker push ghcr.io/40docs/devcontainer:latest
