---
name: Build and Push devcontainer

on:
  repository_dispatch:
    types: [features]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/devcontainer/.devcontainer/devcontainer.json'
      - 'src/devcontainer/devcontainer-template.json'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push:
    timeout-minutes: 1440
    runs-on: template_runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free Disk Space Manual
        run: |
          sudo apt-get remove -y --allow-remove-essential aria2 shellcheck rpm xorriso \
            zsync gfortran-9 nginx shim-signed imagemagick libmagickcore-dev \
            libmagickwand-dev libmagic-dev ant ant-optional kubectl \
            mercurial apt-transport-https unixodbc-dev yarn libssl-dev snapd \
            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
            snmp pollinate libpq-dev ruby-full subversion microsoft-edge-stable || true

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
        with:
          platforms: "linux/amd64"

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
        with:
          use: true
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: "ghcr.io"
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainer
          #cacheFrom: ghcr.io/${{ github.repository_owner }}/devcontainer
          subFolder: src/devcontainer
          platform: linux/amd64
          push: always
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
